#!/bin/sh

set -e

gammu_man2html()
{
    man2html -r $1 \
    | sed 's/&\(nbsp\|copy\|lt\|gt\|#169\);/X-\1-X/g' \
    | recode HTML..iso-8859-1 \
    | sed 's/X-\([a-z#0-9]*\)-X/\&\1;/g;' \
    |  sed '
        1d; 
        s@<HEAD>@<HEAD><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />@;
        s@<A HREF="/cgi-bin/man/man2html">man2html</A>@man2html@g; 
        s@<A HREF="../man[157]/\(wammu[^"]*\|gammu[^"]*\|jadmaker[^"]*\)">\([^<]*\)</A>@<a href="\1">\2</a>@g;' \
    |  sed '
        s@<A HREF="../man[157]/.*">\([^<]*\)</A>@\1@g;
        ' | tidy -asxhtml -utf8 -  > $2 2> /dev/null || true
}


for man in `find ../gammu/docs/user/ ../wammu -name '*[a-z].1' -o -name '*[a-z].5' -o -name '*[a-z].7'` ; do
    page=`basename $man`
    lang=$(basename $(dirname $man))
    if [ $lang = user -o $lang = wammu ] ; then
        lang="en"
    fi
    echo $lang/$page
    mkdir -p ./tmp-man/$lang
    mkdir -p html/docs/man/$lang
    gammu_man2html $man ./tmp-man/$lang/$page.html
    ./process_man.py ./tmp-man/$lang/$page.html > html/docs/man/$lang/$page.html
done

rm -rf tmp-man
