# Generated by Django 1.10.3 on 2016-12-14 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0002_auto_20161214_0845"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="post_tweet",
        ),
    ]
