# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_remove_release_post_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='sha256',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
