# Generated by Django 1.10.6 on 2017-03-17 09:30

import hashlib
import os

from django.conf import settings
from django.db import migrations


def add_sha256(apps, schema_editor):
    downloads = apps.get_model("downloads.Download").objects.filter(sha256="")

    for download in downloads.iterator():
        filename = os.path.join(settings.FILES_ROOT, download.location.lstrip("/"))

        if not os.path.exists(filename):
            print(f"File not found: {filename}")
            continue

        with open(filename) as handle:
            data = handle.read()

            sha256 = hashlib.sha256()
            sha256.update(data)
            download.sha256 = sha256.hexdigest()

        download.save()


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0004_download_sha256"),
    ]

    operations = [migrations.RunPython(add_sha256)]
