# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:30
from __future__ import unicode_literals
from __future__ import print_function

import hashlib
import os

from django.db import migrations
from django.conf import settings


def add_sha256(apps, schema_editor):
    downloads = apps.get_model('downloads.Download').objects.filter(sha256='')

    for download in downloads.iterator():
        filename = os.path.join(settings.FILES_ROOT, download.location.lstrip('/'))

        if not os.path.exists(filename):
            print('File not found: {0}'.format(filename))
            continue

        with open(filename, 'r') as handle:
            data = handle.read()

            sha256 = hashlib.sha256()
            sha256.update(data)
            download.sha256 = sha256.hexdigest()

        download.save()


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_download_sha256'),
    ]

    operations = [
        migrations.RunPython(add_sha256)
    ]
