# Generated by Django 1.11 on 2017-04-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0005_auto_20170317_0930"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="release",
            options={"ordering": ["-date"]},
        ),
    ]
