# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170512010505 on 2017-06-14 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0006_auto_20170407_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['platform', 'location']},
        ),
    ]
