# Generated by Django 1.11 on 2017-04-07 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phonedb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phone",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["name"]},
        ),
    ]
