# Generated by Django 3.1.2 on 2020-10-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonedb', '0003_auto_20200305_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='tuxmobil',
        ),
    ]
