# Generated by Django 3.1.6 on 2021-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phonedb", "0004_remove_vendor_tuxmobil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
