name: ruff

permissions:
  contents: read

on:
  push:
    branches-ignore:
    - dependabot/**
    - weblate
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements-lint.txt
    - name: Run ruff
      run: |
        pre-commit run ruff --all
